version: '3.3'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  parser:
    image: dedrobin/onliner-parser:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - DATABASE_HOST=postgres
      - DB_ECHO=${DB_ECHO}
    command: |
      python run_app.py